syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.gRPCAttempt.gRPC.peopleimage";
// option java_outer_classname = "GreetProto";

package peopleimage;

import "enums.proto";

message PersonImageBytesProtobufDTO {
    int64 id = 1;
    string identificationNumber = 2;
    string passportNumber = 3;
    string email = 4;
    string name = 5;
    int32 age = 6;
    people.Nations nationality = 7;
    people.Nations currentCountry = 8;
    people.MaritalStatus maritalStatus = 9;
    int32 children = 10;
    bytes biometrics = 11;
}

message PersonImageBytesProtobufListDTO {
    repeated PersonImageBytesProtobufDTO personImageBytesProtobufListDTO = 1;
}