printf "TESTING gRPC performance (reflection used)\n"
printf "POST grpcurl\n"
printf "\n"

./grpcurl -plaintext localhost:9090 list;
printf "\n"

./grpcurl -plaintext localhost:9090 describe people.PeopleInfo;
printf "\n"

./grpcurl -plaintext -d '{"nationality":"SG"}' localhost:9090 people.PeopleInfo/Nationality;

./grpcurl -plaintext -d '{"identificationNumber":"987-56-3201", "passportNumber":"509823641", "nationality":"US"}' localhost:9090 people.PeopleInfo/Person;

./grpcurl -plaintext -d '{"nationality":"SG"}' localhost:9090 people.PeopleInfo/PeopleEmail;


printf "people.PeopleInfo/Nationality;\n"

./grpcurl -plaintext -d '{"nationality":"AD"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"AE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"AR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"AT"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"AU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"BA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"BB"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"BE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"BG"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"BO"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"BR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CH"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CI"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CL"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CM"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CN"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CO"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CS"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CY"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"CZ"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"DD"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"DE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"DK"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"EC"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"EE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"EG"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"ES"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"FI"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"FR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"GB"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"GE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"GR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"HK"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"HR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"HU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"ID"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IL"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IN"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IQ"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IS"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"IT"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"JM"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"JO"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"JP"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"KE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"KR"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"KW"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"KZ"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"LB"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"LT"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"LU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"LV"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"MA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"MC"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"MX"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"MY"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"NA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"NL"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"NO"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"NZ"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"OM"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"PE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"PH"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"PL"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"PS"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"PT"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"PY"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"QA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"RO"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"RS"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"RU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"RW"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SG"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SI"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SK"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SM"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"SU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"TH"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"TU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"TW"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"TZ"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"UA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"UG"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"US"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"UY"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"VE"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"XX"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"YU"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"ZA"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"ZM"}' localhost:9090 people.PeopleInfo/Nationality;
./grpcurl -plaintext -d '{"nationality":"ZW"}' localhost:9090 people.PeopleInfo/Nationality;


printf "people.PeopleInfo/PeopleEmail;\n"

./grpcurl -plaintext -d '{"nationality":"AD"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"AE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"AR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"AT"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"AU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"BA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"BB"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"BE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"BG"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"BO"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"BR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CH"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CI"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CL"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CM"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CN"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CO"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CS"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CY"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"CZ"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"DD"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"DE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"DK"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"EC"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"EE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"EG"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"ES"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"FI"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"FR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"GB"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"GE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"GR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"HK"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"HR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"HU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"ID"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IL"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IN"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IQ"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IS"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"IT"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"JM"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"JO"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"JP"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"KE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"KR"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"KW"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"KZ"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"LB"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"LT"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"LU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"LV"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"MA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"MC"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"MX"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"MY"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"NA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"NL"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"NO"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"NZ"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"OM"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"PE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"PH"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"PL"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"PS"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"PT"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"PY"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"QA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"RO"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"RS"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"RU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"RW"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SG"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SI"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SK"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SM"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"SU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"TH"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"TU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"TW"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"TZ"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"UA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"UG"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"US"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"UY"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"VE"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"XX"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"YU"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"ZA"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"ZM"}' localhost:9090 people.PeopleInfo/PeopleEmail;
./grpcurl -plaintext -d '{"nationality":"ZW"}' localhost:9090 people.PeopleInfo/PeopleEmail;

./grpcurl -plaintext -d '{"identificationNumber":"987-56-3201", "passportNumber":"509823641", "nationality":"US"}' localhost:9090 people.PeopleInfo/Person;
