syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.Mutlithreading_Tester.gRPC.people";
// option java_outer_classname = "GreetProto";

package people;

import "enums.proto";

message PersonProtobufDTO {
    int64 id = 1;
    string identificationNumber = 2;
    string passportNumber = 3;
    string email = 4;
    string name = 5;
    int32 age = 6;
    Nations nationality = 7;
    Nations currentCountry = 8;
    MaritalStatus maritalStatus = 9;
    int32 children = 10;
}

message PersonProtobufListDTO {
    repeated PersonProtobufDTO personProtobufListDTO = 1;
}